name: Build Web Export

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

env:
  GODOT_VERSION: "4.5"
  PROJECT_PATH: "."

jobs:
  build:
    name: Web Export
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot export templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          if [ -d /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ]; then
            mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
          fi
          mkdir -p ~/.config/
          if [ -d /root/.config/godot ]; then
            mv /root/.config/godot ~/.config/godot
          fi

      - name: Export Web build
        run: |
          mkdir -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd "${PROJECT_PATH}"
          godot --headless --verbose --export-release "Web" "${EXPORT_DIR}/web/index.html"

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
